// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oudlivqtsurpdafguwqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91ZGxpdnF0c3VycGRhZmd1d3FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5NzAxMDQsImV4cCI6MjA4ODU0NjEwNH0.DU7TU1UUTKXLu2_h41Dk2kD852Z56jGtPMHAJHGaJ0Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});