// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cyjitwvncgfrzyyhyiqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5aml0d3ZuY2dmcnp5eWh5aXFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNTcwMTAsImV4cCI6MjA3MDkzMzAxMH0.1Oi-8WRLnzKS9t2bwATdXAI8Bslkx6wDuCAQk1lRkts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});